config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'

  resources :users
  resources :posts
  resources :user_sessions
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  post_date  :date
#  content    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  is_impressionable

  belongs_to :user
  has_many :post_tags
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :content, presence: true
end

app/models/post_tag.rb
# == Schema Information
#
# Table name: post_tags
#
#  id         :integer          not null, primary key
#  post_id    :integer
#  tag_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  email            :string           not null
#  crypted_password :string
#  salt             :string
#  name             :string
#  twitter          :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_popular_tags
  impressionist

  private

  def not_authenticated
    redirect_to new_user_session_path
  end

  def set_popular_tags
    @popular_tags = PostTag.group(:tag_id).
                            order('count(*) DESC').
                            limit(5).
                            count.
                            keys.
                            map { |tag_id| Tag.find(tag_id) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :create, :edit, :update]

  def index
    @popular_posts = Impression.where(controller_name: 'posts', action_name: 'show')
    .group(:impressionable_id).order('count(*) DESC').limit(8).count.keys
    .map { |id| Post.find(id)}
    @new_posts = Post.order('created_at DESC').limit(8)
  end

  def show
  end

  def new
    @post = current_user.posts.new
    @hide_sidebar = true
  end

  def edit
    @hide_sidebar = true
  end

  def create
    @post = current_user.posts.new(target_params)
    tags = params[:tags].split(',').map { |tag| Tag.find_or_create_by(name: tag) }
    @post.tags = tags
    if @post.save
      redirect_to posts_path
    else
      flash.now[:alert] = '投稿に失敗しました。'
      render action: :new
    end
  end

  def update
    if @post.update(target_params)
      redirect_to post_path(@post)
    else
      flash.now[:alert] = '更新に失敗しました。'
      render action: :edit
    end
  end

  def destroy
    @post.destroy
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def target_params
      params.require(:post).permit(:title, :post_date, :content)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  def show
    @posts = @tag.posts
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      flash.now[:alert] = 'ログインしました。'
      redirect_to posts_path
    else
      @user = User.new
      flash.now[:alert] = 'ログインに失敗しました。'
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(target_params)

    if @user.save
      redirect_to posts_path
    else
      redirect_to posts_path
    end
  end

  def destroy
  end

  def edit
  end

  private

  def target_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :name,
      :twitter
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metatags_helper.rb
module MetatagsHelper
  def self.default_meta_tags
    {
      site: 'Failer',
      title: 'Failer',
      reverse: true,
      charset: 'utf-8',
      description: '失敗談をまとめたサイトです。',
      keywords: '失敗談,失敗,まとめ',
      canonical: ENV['ORIGIN_URL'],
      separator: '|',
      # icon: [
      #   { href: image_url('favicon.ico') },
      #   { href: image_url('icon.jpg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      # ],
      og: {
        site_name: 'Failer',
        title: 'Failer',
        description: '失敗談をまとめたサイトです。',
        type: 'website',
        url: ENV['ORIGIN_URL'],
        # image: image_url('ogp.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary',
        site: 'Failer',
      }
    }
  end
end

app/views/layouts/_header.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to '失敗談まとめ', root_path %></h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to '失敗談を投稿する', new_post_path, class: 'btn btn-primary' %>
  </nav>
  <% if current_user %>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.name %>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to 'ログアウト', user_session_path(current_user), class: 'dropdown-item', method: 'DELETE' %>
      </div>
    </div>
  <% else %>
    <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-outline-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Failers</title>
    <%= display_meta_tags MetatagsHelper.default_meta_tags %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
  </head>

  <body class="bg-light">
    <%= render 'layouts/header' %>
    <div>
      <% if flash[:alert] %>
        <p class="alert alert-primary"><%= flash[:alert] %></p>
      <% end %>
    </div>
    <main role="main" class="container">
      <div class="row">
        <div class="<%= @hide_sidebar ? 'col-12' : 'col-8' %>">
          <%= yield %>
        </div>
        <div class="col-4" <%= 'style="display: none;"' unless @hide_sidebar %>>
          <div class="bg-white rounded box-shadow p-3 my-3">
            <h6 class="pb-1">人気のタグ</h6>
            <ul class="list-group list-group-flush">
              <% @popular_tags.each_with_index do |tag, i| %>
                <%= link_to tag_path(tag) do %>
                  <li class="list-group-item">
                    <span class="text-muted pr-2"><%= i + 1 %></span>
                    <span class="text-body"><%= tag.name %></span>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/posts/_form.slim
.my-3.p-3.bg-white.rounded.box-shadow
  br
  = form_for @post do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :tags
      = text_field_tag :tags, nil, id: 'js-tagsinput'
    .form-group
      = f.label :content
      = f.text_area :content, id: 'summernote'
    .form-group
      = f.submit '投稿する', class: 'btn btn-primary'

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

<%= link_to '投稿をみる', @post %> |
<%= link_to '戻る', posts_path %>

app/views/posts/index.html.erb
<div class="my-3 p-3 bg-white rounded box-shadow">
  <h6 class="border-bottom border-gray pb-2 mb-0">人気の投稿</h6>
  <% @popular_posts.each do |post| %>
    <%= link_to post_path(post) do %>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" src="https://placehold.jp/150x150.png" data-holder-rendered="true" style="width: 32px; height: 32px;">
        <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray" style="overflow: hidden;">
          <div class="d-flex justify-content-between align-items-center w-100">
            <strong class="text-gray-dark"><%= post.title %></strong>
          </div>
          <% post.tags.each do |tag| %>
            <span class="badge badge-secondary">
              <%= tag.name %>
            </span>
          <% end %>
          <br>
          <div class="content">
            <%= excerpt post.content, '', radius: 100 %>
          </div>
          <span class="d-block">by <%= post.user.name %> <%= post.created_at.strftime('%Y %m月%d日') %></span>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="my-3 p-3 bg-white rounded box-shadow">
  <h6 class="border-bottom border-gray pb-2 mb-0">最新の投稿</h6>
  <% @new_posts.each do |post| %>
    <%= link_to post_path(post) do %>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" src="https://placehold.jp/150x150.png" data-holder-rendered="true" style="width: 32px; height: 32px;">
        <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray" style="overflow: hidden;">
          <div class="d-flex justify-content-between align-items-center w-100">
            <strong class="text-gray-dark"><%= post.title %></strong>
          </div>
          <% post.tags.each do |tag| %>
            <span class="badge badge-secondary">
              <%= tag.name %>
            </span>
          <% end %>
          <br>
          <div class="content">
            <%= excerpt post.content, '', radius: 100 %>
          </div>
          <span class="d-block">by <%= post.user.name %> <%= post.created_at.strftime('%Y %m月%d日') %></span>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to '戻る', posts_path %>

app/views/posts/show.slim
- set_meta_tags title: @post.title, description: (excerpt @post.content, '', radius: 100), og: {title: @post.title, type: 'article'}

.my-3.p-3.bg-white.rounded.box-shadow
  .media.text-muted
    = image_tag 'https://placehold.jp/150x150.png', class: 'mr-2 rounded', style: 'width: 32px; height: 32px;'
    .media-body
      span.mr-2 = @post.user.name
      span = @post.created_at.strftime('%Y年%m月%d日')
      | に投稿
  h2.pt-4 = @post.title
  - @post.tags.each do |tag|
    span.badge.badge-secondary
      = tag.name
  .mt-4
    = simple_format @post.content

app/views/tags/show.slim
.my-3.p-3.bg-white.rounded.box-shadow
  h6.border-bottom.border-gray.pb-2.mb-0
    = "「#{ @tag.name }」の投稿"
  - @posts.each do |post|
    = link_to post_path(post) do
      .media.text-muted.pt-3
        img.mr-2.rounded alt="32x32" data-holder-rendered="true" data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" src="https://placehold.jp/150x150.png" style=("width: 32px; height: 32px;") /
        .media-body.pb-3.mb-0.small.lh-125.border-bottom.border-gray
          .d-flex.justify-content-between.align-items-center.w-100
            strong.text-gray-dark= post.title
          - post.tags.each do |tag|
            span.badge.badge-secondary
              = tag.name
          br/
          = post.content
          span.d-block
            | by #{post.user.name} #{post.created_at.strftime('%Y %m月%d日')}

app/views/user_sessions/new.slim
.my-3.p-3.bg-white.rounded.box-shadow
  h3 ログイン
  br
    = form_tag user_sessions_path, method: :post do |f|
      .form-group
        = label_tag :メールアドレス
        = email_field_tag :email, nil, class: 'form-control', required: :required
      .form-group
        = label_tag :パスワード
        = password_field_tag :password, nil, class: 'form-control', required: :required
      .form-group
        = submit_tag 'ログイン', class: 'btn btn-primary'
        = link_to '新規会員登録', new_user_path, class: 'btn btn-default'

app/views/users/new.slim
.my-3.p-3.bg-white.rounded.box-shadow
  h3 新規ユーザー登録
  = form_for @user do |f|
    .form-group
      = f.label :email
      = f.email_field :email, class: 'form-control', required: :required
    .form-group
      = f.label :password
      = f.password_field :password, class: 'form-control', required: :required
    .form-group
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control', required: :required
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control', required: :required
    .form-group
      = f.submit '会員登録', class: 'btn btn-primary'
      = link_to 'ログイン', new_user_session_path, class: 'btn btn-default'